### ISSUE TITLE
Error when creating a Project on Azure

### ISSUE THREAD

**Issue by malperovich** [epam/cloud-pipeline#108]
When I try (using Azure) to create a Project, an error message pops up
![ProjectError](https://user-images.githubusercontent.com/17769194/55909219-71e5d880-5ba9-11e9-860f-e2ae2a3a8302.PNG)
saying the data storage already exists, while that couldn't be true because I'm using unique project names

**Comment by sidoruka** [comment]
Version: `0.15.0.117.03e2698b06c52ce76594272dd147e75b6a4941dd`

**Comment by sidoruka** [comment]
* Same issue using `0.15.0.386.e92469bf68cf62933d673561d59d1f93c1ad94a7`
* AWS works fine with the same configuration
* Folder template:
```
{
    "name": "@@",
    "metadata": {
        "type": {
            "value": "project"
        },
         "DataStorage": {
            "value": "az://cloud-pipeline-@@-storage",
            "type": "bucket"
        },
         "ProjectID": {
            "value": "@@"
        }
    },
    "children": [
        {
            "name": "Method-Configurations"
        }
    ],
    "datastorages": [
        {
            "name": "@@-storage",
            "path": "cloud-pipeline-@@-storage",
            "serviceType" : "OBJECT_STORAGE"
        }
    ]
}
```

* API logs:
```
java.lang.IllegalStateException: Error: data storage with name: 'test-new-proj-random-id-123-123-storage' or path: 'cloud-pipeline-test-new-proj-random-id-123-123-storage' already
 exists.
        at com.epam.pipeline.manager.pipeline.FolderTemplateManager.verifyDataStorageNonExistence(FolderTemplateManager.java:218) ~[classes!/:0.15.0.386.e92469bf68cf62933d673561d5
9d1f93c1ad94a7]
        at com.epam.pipeline.manager.pipeline.FolderTemplateManager.lambda$prepareTemplateStorages$3(FolderTemplateManager.java:147) ~[classes!/:0.15.0.386.e92469bf68cf62933d67356
1d59d1f93c1ad94a7]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_201]
        at com.epam.pipeline.manager.pipeline.FolderTemplateManager.prepareTemplateStorages(FolderTemplateManager.java:136) ~[classes!/:0.15.0.386.e92469bf68cf62933d673561d59d1f93
c1ad94a7]
        at com.epam.pipeline.manager.pipeline.FolderTemplateManager.prepareTemplate(FolderTemplateManager.java:179) ~[classes!/:0.15.0.386.e92469bf68cf62933d673561d59d1f93c1ad94a7
]
        at com.epam.pipeline.manager.pipeline.FolderTemplateManager.create(FolderTemplateManager.java:98) ~[classes!/:0.15.0.386.e92469bf68cf62933d673561d59d1f93c1ad94a7]
        at com.epam.pipeline.manager.pipeline.FolderTemplateManager$$FastClassBySpringCGLIB$$b035acbc.invoke(<generated>) ~[classes!/:0.15.0.386.e92469bf68cf62933d673561d59d1f93c1
ad94a7]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
```
