### ISSUE TITLE
Command pipe set-acl doesn't work in pipe CLI for Windows

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#1130]
**Describe the bug**
Command pipe set-acl doesn't work in pipe CLI for Windows

**To Reproduce**

    Install CLI for Windows. Perform the CLI pipe set-acl command, e.g.:
        pipe set-acl -t folder -s <User_Name> -d wx -a r <folder_name>

**Actual behavior**
Error:
```
Traceback (most recent call last):
  File "pipe-cli\pipe.py", line 1332, in <module>
  File "site-packages\click\core.py", line 722, in __call__
  File "site-packages\click\core.py", line 697, in main
  File "site-packages\click\core.py", line 1066, in invoke
  File "site-packages\click\core.py", line 895, in invoke
  File "site-packages\click\core.py", line 535, in invoke
  File "site-packages\click\decorators.py", line 17, in new_func
  File "pipe-cli\src\config.py", line 122, in validate_access_token_wrapper
  File "site-packages\click\core.py", line 535, in invoke
  File "pipe-cli\pipe.py", line 1081, in set_acl
  File "pipe-cli\src\utilities\acl_operations.py", line 46, in set_acl
TypeError: object of type 'filter' has no len()
[26960] Failed to execute script pipe
```
Note: It works correctly in SSH.

**Expected behavior**
Permissions set

**Environment:**
 - Cloud Provider: N/A
 - Version  0.16.0.5454

**Comment by maryvictol** [comment]
Verified and closed (Cloud Pipeline CLI, version 0.16.0.5479).
