### ISSUE TITLE
Support autonomous data synchronization in DTS

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#2044]
**Background**

The following tasks are required to support autonomous data synchronization in DTS.

# @Wedds

@Wedds Could you please implement the following tasks?

**API**
1. [x] Add support for DTS specific preferences
    Add specific preferences field to DTS table and add API methods for DTS specific preferences upsert and delete operations.
1. [x] Expose DTS resources via static files
    Expose data-transfer-service.jar via static files in /deploy/docker/cp-api-srv/init-api and expose DTS launcher script via static files.

**CLI**
1. [x] Add support for `pipe dts create` command
1. [x] Add support for `pipe dts list` command
1. [x] Add support for `pipe dts list [dts id or dts name]` command
    The command shall show all DTS specific preferences as well as common single dts information
1. [x] Add support for `pipe dts update [dts id or dts name] [preference name] [preference value]` command
1. [x] Add support for `pipe dts delete [dts id or dts name] [preference name]` command

**DTS**
1. [x] Add support for DTS specific preferences synchronization
    Create DTS specific preferences watcher which will constantly download all DTS specific preferences and provide them to all java managers in a thread-safe manner. All java managers should not fail if some required DTS specific preferences are missing.
1. [x] Add support for graceful application shutdown on restart=true DTS specific preference
1. [x] Add support for local / cloud directory synchronization
        It should upload all file which were modified since the previous successful synchronization. Several independent synchronization directories should be supported. Synchronization should start by DTS specific cron.

#  @tcibinan

Tasks for myself

**DTS**
1. [x] Embed java to data-transfer-service.jar using gradle

**DTS launcher**
1. [x] Create simple powershell script which downloads DTS + pipe and starts DTS
1. [x] Add support for powershell script self-registration as scheduled task

**Comment by maryvictol** [comment]
**Comments:**

1. [ ] If `DTS_NAME` isn't specified then command `pipe dts preferences update "$DTS_NAME" -p 'dts.local.sync.rules=[....]` gives unclear error message 
```
Traceback (most recent call last):
  File "pipe-cli/pipe.py", line 1804, in <module>
  File "pipe-cli/src/utilities/custom_abort_click_group.py", line 38, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "pipe-cli/pipe.py", line 1787, in update_dts_preferences
  File "pipe-cli/src/utilities/dts_operations_manager.py", line 51, in upsert_preferences
  File "pipe-cli/src/api/dts.py", line 64, in update_preferences
  File "pipe-cli/src/api/base.py", line 83, in call
  File "pipe-cli/src/api/base.py", line 154, in _build_response_data
RuntimeError: Failed to fetch data from server. Server responded with message: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "preferences"
[1592] Failed to execute script pipe
```
1. [ ] Timestamp for `DtsSynchronizationService - Running transfer task from` is given in another format
![image](https://user-images.githubusercontent.com/47791878/125767394-41601e44-db33-4981-b5df-e00260099930.png)
1. [ ] No message is shown at case of both `source` folder and storage don't exist.
1. [ ] At case of incorrect `cron` value is specified for at least one of rule in `dts.local.sync.rules` all rules don't work. No error message about incorrect value is shown in the log.
1. [x] If there is no any registered DTS, command `pipe dts list` gives error message:
```
Traceback (most recent call last):
  File "pipe-cli/pipe.py", line 1804, in <module>
  File "pipe-cli/src/utilities/custom_abort_click_group.py", line 38, in _call_
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "pipe-cli/src/config.py", line 133, in validate_access_token_wrapper
  File "site-packages/click/core.py", line 535, in invoke
  File "pipe-cli/pipe.py", line 1768, in list_dts
  File "pipe-cli/src/utilities/dts_operations_manager.py", line 41, in list
  File "pipe-cli/src/api/dts.py", line 46, in load_all
TypeError: 'NoneType' object is not iterable
[892] Failed to execute script pipe
```
