### ISSUE TITLE
[pipe] SSH tunnel is not being created

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#2351]
**Describe the bug**
I've tried to create SSH tunnel to the running instance via the Windows PowerShell/Command Prompt/WSL.
Attempts to perform `pipe tunnel start <RUN_ID> -lp 4567 -rp 22 --ssh` command:
- in Windows PowerShell/Command Prompt are failed with the following error: `Error: psutil.AccessDenied (pid=3312, name='python2.7')`. Traceback:
```
Traceback (most recent call last):
  File "site-packages\psutil\_pswindows.py", line 780, in cmdline
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\psutil\_pswindows.py", line 679, in wrapper
  File "site-packages\psutil\_pswindows.py", line 695, in wrapper
  File "site-packages\psutil\_pswindows.py", line 783, in cmdline
PermissionError: [Errno 13] Access denied (originated from NtQueryInformationProcess(ProcessBasicInformation) -> STATUS_NOT_FOUND translated into PermissionError)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipe-cli\pipe.py", line 149, in stacktracing
  File "site-packages\click\core.py", line 535, in invoke
  File "site-packages\click\decorators.py", line 17, in new_func
  File "pipe-cli\pipe.py", line 137, in _wrapper
  File "pipe-cli\pipe.py", line 168, in console_logging
  File "site-packages\click\core.py", line 535, in invoke
  File "site-packages\click\decorators.py", line 17, in new_func
  File "pipe-cli\pipe.py", line 137, in _wrapper
  File "pipe-cli\pipe.py", line 185, in signals_handling
  File "site-packages\click\core.py", line 535, in invoke
  File "site-packages\click\decorators.py", line 17, in new_func
  File "pipe-cli\pipe.py", line 137, in _wrapper
  File "pipe-cli\pipe.py", line 210, in frozen_locking
  File "site-packages\click\core.py", line 535, in invoke
  File "site-packages\click\decorators.py", line 17, in new_func
  File "pipe-cli\pipe.py", line 137, in _wrapper
  File "pipe-cli\pipe.py", line 201, in resources_cleaning
  File "site-packages\click\core.py", line 535, in invoke
  File "site-packages\click\decorators.py", line 17, in new_func
  File "pipe-cli\src\config.py", line 133, in validate_access_token_wrapper
  File "site-packages\click\core.py", line 535, in invoke
  File "pipe-cli\pipe.py", line 248, in _wrapper
  File "pipe-cli\pipe.py", line 1728, in start_tunnel
  File "pipe-cli\src\utilities\ssh_operations.py", line 451, in create_tunnel
  File "pipe-cli\src\utilities\ssh_operations.py", line 482, in check_existing_tunnels
  File "pipe-cli\src\utilities\ssh_operations.py", line 1260, in find_tunnel_procs
  File "site-packages\psutil\__init__.py", line 675, in cmdline
  File "site-packages\psutil\_pswindows.py", line 681, in wrapper
psutil.AccessDenied: psutil.AccessDenied (pid=3312, name='python2.7')
```
- in WSL are failed with the following error: `RuntimeError: Failed to serve tunnel in background. Tunnel is not initialized after 300 seconds.`

**To Reproduce**
1. Run a launch, wait until the SSH hyperlink will appear at the **Run logs** page
2. Open Windows PowerShell/Command Prompt/WSL
3. Configure `pipe CLI`
4. Perform command `pipe tunnel start <RUN_ID> -lp 4567 -rp 22 --ssh`, where `<RUN_ID>` is the ID of the run launched at step 1
5. See error

**Expected behavior**
Command is performed without errors

**Environment:**
 - Cloud Provider: AWS
 - Versions: **0.17.0.11245**

**Comment by tcibinan** [comment]
Should be fixed with 6536e677bbee7e98d5371d63e81fbd76c0a2dc10.

**Comment by tcibinan** [comment]
Cherry-picked to `release/0.16` via 0d6aa2859ff961408efd0145ca34641d471c3d34.

**Comment by NShaforostov** [comment]
Verified. Fixed.
SSH Tunnel is being created without errors (checked in Windows PowerShell and WSL)
