### ISSUE TITLE
ElasticsearchAgentService: Could not resolve type id 'AZ' 

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#24]
Seems that indexing daemon is not fully ported for the Azure BLOB storages

```
[WARN ] 2019-03-27 18:59:45.047 [pool-3-thread-1] ElasticsearchAgentService - Exception while trying to send data to Elasticsearch service
java.util.concurrent.CompletionException: com.epam.pipeline.exception.PipelineResponseException: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'AZ' as a subtype of [simple type, class com.epam.pipeline.entity.datastorage.AbstractDa
taStorage]: known type ids = [NFS, S3] (for POJO property 'payload')
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 167] (through reference chain: com.epam.pipeline.rest.Result["payload"]->java.util.ArrayList[0])
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.epam.pipeline.exception.PipelineResponseException: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'AZ' as a subtype of [simple type, class com.epam.pipeline.entity.datastorage.AbstractDataStorage]: known type ids = [N
FS, S3] (for POJO property 'payload')
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 167] (through reference chain: com.epam.pipeline.rest.Result["payload"]->java.util.ArrayList[0])
        at com.epam.pipeline.utils.QueryUtils.execute(QueryUtils.java:60) ~[model-0.15.0.246.jar!/:?]
        at com.epam.pipeline.elasticsearchagent.service.impl.CloudPipelineAPIClient.loadAllDataStorages(CloudPipelineAPIClient.java:64) ~[classes!/:0.15.0.246]
        at com.epam.pipeline.elasticsearchagent.service.impl.S3Synchronizer.synchronize(S3Synchronizer.java:76) ~[classes!/:0.15.0.246]
        at com.epam.pipeline.elasticsearchagent.service.ElasticsearchAgentService.lambda$null$0(ElasticsearchAgentService.java:85) ~[classes!/:0.15.0.246]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_201]
        ... 3 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'AZ' as a subtype of [simple type, class com.epam.pipeline.entity.datastorage.AbstractDataStorage]: known type ids = [NFS, S3] (for POJO property 'payload')
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 167] (through reference chain: com.epam.pipeline.rest.Result["payload"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1628) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1186) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:291) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:162) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:288) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32) ~[converter-jackson-2.4.0.jar!/:?]
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23) ~[converter-jackson-2.4.0.jar!/:?]
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122) ~[retrofit-2.4.0.jar!/:?]
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217) ~[retrofit-2.4.0.jar!/:?]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) ~[retrofit-2.4.0.jar!/:?]
        at com.epam.pipeline.utils.QueryUtils.execute(QueryUtils.java:46) ~[model-0.15.0.246.jar!/:?]
        at com.epam.pipeline.elasticsearchagent.service.impl.CloudPipelineAPIClient.loadAllDataStorages(CloudPipelineAPIClient.java:64) ~[classes!/:0.15.0.246]
        at com.epam.pipeline.elasticsearchagent.service.impl.S3Synchronizer.synchronize(S3Synchronizer.java:76) ~[classes!/:0.15.0.246]
        at com.epam.pipeline.elasticsearchagent.service.ElasticsearchAgentService.lambda$null$0(ElasticsearchAgentService.java:85) ~[classes!/:0.15.0.246]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_201]
        ... 3 more
```

**Comment by mzueva** [comment]
@rodichenko new search result type `AZ_BLOB_FILE` was added, please check whether any changes shall be added to the client code.
