### ISSUE TITLE
The run failed with "NodeLost" status

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#285]
**NOTE**: Such behavior doesn't appear constantly, "flaky" bug.
    
- Environment: AZURE  
- Version:  0.15.0.944.582d8809f2
- Step to reproduce:

    1. Create a shell template pipeline
    2. Launch the created pipeline
    4. Click on the just-launched run at "ACTIVE RUNS" tab on Runs page

**Exp**.: The run is running
**Act**.: The run failed with "NodeLost" status and run tasks were not executed

![image](https://user-images.githubusercontent.com/23356251/57775772-73fe0280-7726-11e9-83ad-e4084e6470b2.png)

As we can see from pipeline logs:

`AutoscaleManager - Failed to load pipeline run 1297.
[ERROR] 2019-05-15 00:21:33.258 [taskScheduler-3] AutoscaleManager - Pipeline with requested id: '1,297' was not found.
java.lang.IllegalArgumentException: Pipeline with requested id: '1,297' was not found.
	at org.springframework.util.Assert.notNull(Assert.java:134) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at com.epam.pipeline.manager.pipeline.PipelineRunManager.loadPipelineRun(PipelineRunManager.java:380)`

**Comment by NShaforostov** [comment]
Occurred again while performing daily e2e-tests:

Data | CloudPipeline version
---|---
16.05.2019 | 0.15.0.990.c53a6b809133f0d3b56359e8e05b2477465c7823
04.06.2019 (thrice) | 0.16.0.1312.a2c274bc0fcb52b379144db763ceff6ea432fe02
05.06.2019 | 0.16.0.1320.29fbd02757b9e2422645e69c721e1e03fdfcb457
20.06.2019 | 0.16.0.1453.3e9b95b124ba269b788f2593c3eb1332013b5215
24.06.2019 | 0.16.0.1491.2ac89bc4fb22dd555568c0229356eb2db2c4b455
23.07.2019 | 0.16.0.1900.4a2c62f1ab205347fdf6ccb13ea5719176c2f43c
14.08.2019 | 0.16.0.2214.feb65d1cbcb984463c8be3a5e2ee6994e7741769
12.09.2019 | 0.16.0.2484.88174633365cd89342ab7fab799702411b543401
08.10.2019 | 0.16.0.2910.a79bedf9ed47037320b7ff86ea53b94b099794f3
10.10.2019 | 0.16.0.2938.b39e1318156277bf71fa30a84ca98506f20522ce
11.10.2019 | 0.16.0.2975.8b2637d8eb4b4828e50fe9f2fbc6b99b13a6c886

See issue #397 for more details
