### ISSUE TITLE
Instance usage monitor fails with NPE

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#459]
`ResourceMonitorManager` class fails with NPE:

`[ERROR] 2019-06-27 11:30:56.286 [taskScheduler-1] TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
	at com.epam.pipeline.manager.cluster.performancemonitoring.ResourceMonitoringManager.lambda$processIdleRuns$15(ResourceMonitoringManager.java:203) ~[classes!/:0.16.0.1544.1de827cb547857857aa54267ec7d2af1d03aa3e2]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_201]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_201]
	at com.epam.pipeline.manager.cluster.performancemonitoring.ResourceMonitoringManager.processIdleRuns(ResourceMonitoringManager.java:204) ~[classes!/:0.16.0.1544.1de827cb547857857aa54267ec7d2af1d03aa3e2]
	at com.epam.pipeline.manager.cluster.performancemonitoring.ResourceMonitoringManager.monitorResourceUsage(ResourceMonitoringManager.java:120) ~[classes!/:0.16.0.1544.1de827cb547857857aa54267ec7d2af1d03aa3e2]`

Reproduced on GCP dev environment.

**Comment by mzueva** [comment]
Fixed
