### ISSUE TITLE
NPE while creating the new pipeline

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#720]
**Describe the bug**
NPE is thrown, when creating a new pipeline using the fresh deployment of the platform

**To Reproduce**
1. (use a fresh deployment of the platform: no pipelines exist, gitlab is empty)
2. Start creating a new pipeline (e.g. using `DEFAULT` templates and a `pipeline1` name)
3. Click `Create`
4. `We've encountered a server error` message is shown

**Expected behavior**
The pipeline is created and it's possible to view it in the GitLab GUI

**Screenshots**
```
[ERROR] 2019-10-07 13:35:31.997 [https-jsse-nio-8080-exec-2] ExceptionHandlerAdvice - This operation has been aborted: uri=/pipeline/restapi/pipeline/register;client=10.244.0.1;session=98444BC4118FE1058B3434C9A9B73D48;user=PIPE_ADMIN.
java.lang.NullPointerException: null
        at com.epam.pipeline.manager.git.GitManager.getDefaultGitlabClient(GitManager.java:735) ~[classes!/:0.16.0.2877.ddc9c1e5f7ffec93edd29b1dcfb5bff353340e7f]
        at com.epam.pipeline.manager.git.GitManager.checkProjectExists(GitManager.java:726) ~[classes!/:0.16.0.2877.ddc9c1e5f7ffec93edd29b1dcfb5bff353340e7f]
        at com.epam.pipeline.manager.pipeline.PipelineManager.create(PipelineManager.java:109) ~[classes!/:0.16.0.2877.ddc9c1e5f7ffec93edd29b1dcfb5bff353340e7f]
        at com.epam.pipeline.manager.pipeline.PipelineManager$$FastClassBySpringCGLIB$$cca79522.invoke(<generated>) ~[classes!/:0.16.0.2877.ddc9c1e5f7ffec93edd29b1dcfb5bff353340e7f]
```

**Environment:**
 - Cloud Provider: AWS
 - Version: 0.16.0.2877.ddc9c1e5f7ffec93edd29b1dcfb5bff353340e7f
 - Browser: Chrome `Version 77.0.3865.90 (Official Build) (64-bit)`

**Comment by mzueva** [comment]
@sidoruka this error will be thrown if SystemPreference `git.user.id` is not specified

**Comment by mzueva** [comment]
@SilinPavel This error is related to method call `GitlabClient.getUser` in `GitlabClient` constructor. At the moment of deployment `pipe_admin` user is not created in Gitlab yet, deployment scripts try to set git preferences and check `SystemPreferences.areGitPreferencesValid` fails.
