### ISSUE TITLE
NPE while running a docker from the CLI

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#88]
* Cloud environment: AWS
* Environment deployed from 72d146bf70c408efd75911d31183caabb612c96a
* Command used to schedule a run:
```
pipe run --docker-image library/ubuntu:latest \
               --instance-type m5.large \
               --instance-disk 50 \
               --CP_CAP_SGE_AUTOSCALE true \
               --cluster_role "master" \
               --CP_CAP_SGE true \
               --quiet \
               --yes
```
* Command output:
```
Failed to fetch data from server. Server responded with message: Your operation has been aborted as we encountered a server problem
```

* API logs:
```
[INFO ] 2019-04-09 09:58:13.795 [https-jsse-nio-8080-exec-2] ToolManager - Getting size of image cp-docker-registry.default.svc.cluster.local:31443/library/ubuntu:latest
[DEBUG] 2019-04-09 09:58:14.046 [https-jsse-nio-8080-exec-2] PipelineRunManager - Retrieved image size: 99473180 b, image size on disk: 1 Gb, total disk size: 51 Gb
[DEBUG] 2019-04-09 09:58:14.238 [https-jsse-nio-8080-exec-2] PipelineRunManager - Expected price per hour: 0.04396388907929262
[ERROR] 2019-04-09 09:58:14.241 [https-jsse-nio-8080-exec-2] ExceptionHandlerAdvice - This operation has been aborted: uri=/pipeline/restapi/run;client=10.244.0.1;session=4E4B40B3AAF61DB95E4B3FB12FDF0370;user=PIPE_ADMIN.
java.lang.NullPointerException: null
        at com.epam.pipeline.manager.execution.CommandBuilder.replaceParameterIfRequired(CommandBuilder.java:104) ~[classes!/:0.15.0.296.72d146bf70c408efd75911d31183caabb612c96a]
        at com.epam.pipeline.manager.execution.CommandBuilder.getTemplateWithFiledPipeConfiguration(CommandBuilder.java:93) ~[classes!/:0.15.0.296.72d146bf70c408efd75911d31183caabb612c96a]
        at com.epam.pipeline.manager.execution.CommandBuilder.build(CommandBuilder.java:64) ~[classes!/:0.15.0.296.72d146bf70c408efd75911d31183caabb612c96a]
        at com.epam.pipeline.manager.execution.PipelineLauncher.launch(PipelineLauncher.java:115) ~[classes!/:0.15.0.296.72d146bf70c408efd75911d31183caabb612c96a]
        at com.epam.pipeline.manager.execution.PipelineLauncher.launch(PipelineLauncher.java:98) ~[classes!/:0.15.0.296.72d146bf70c408efd75911d31183caabb612c96a]
        at com.epam.pipeline.manager.pipeline.PipelineRunManager.launchPipeline(PipelineRunManager.java:327) ~[classes!/:0.15.0.296.72d146bf70c408efd75911d31183caabb612c96a]
        at com.epam.pipeline.manager.pipeline.PipelineRunManager.runCmd(PipelineRunManager.java:200) ~[classes!/:0.15.0.296.72d146bf70c408efd75911d31183caabb612c96a]
        at com.epam.pipeline.manager.pipeline.PipelineRunManager$$FastClassBySpringCGLIB$$10ca950d.invoke(<generated>) ~[classes!/:0.15.0.296.72d146bf70c408efd75911d31183caabb612c96a]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
```

**Comment by sidoruka** [comment]
This issue shall lead to the NPE fix and a correct error message display. 
* API: return a valid error message
* CLI: check for `-cmd` option in the same manner as `-it/-id`

Further improvements on the standalone tools scheduling shall be implemented in #89
