### ISSUE TITLE
`pipe` CLI doesn't work under Windows

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#900]
**Describe the bug**
While trying to perform any `pipe` CLI command under Windows, it fails with the following error:
```
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "c:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[248208] Failed to execute script pyi_rth_pkgres
```

**To Reproduce**
1. Install `pipe` CLI on Windows according to instructions in the System Settings
2. Run in Windows **cmd** any `pipe` command, e.g.: `pipe --version`
3. See the error written above

**Environment:**
 - Cloud Provider: N/A
 - Version 0.16.0.4002
 - OS Windows 10 Enterprise, version 1803, build 17134.1069

**Comment by mzueva** [comment]
backported to 0.15 via 2de7088

**Comment by sidoruka** [comment]
@NShaforostov please verify

**Comment by NShaforostov** [comment]
Verified
